@baseUrl = http://localhost:4004
@service = /odata/v4/catalog
@service2 = /odata/v2/catalog

GET {{baseUrl}}{{service}}/$metadata
Accept: application/xml

###
GET {{baseUrl}}{{service}}/Books
Authorization: Basic viewer:

###
GET {{baseUrl}}{{service}}/Books?$select=ID,title,stock,price,author&$expand=author($select=name)&$orderby=title
Authorization: Basic viewer:
Accept: application/json

###
GET {{baseUrl}}{{service}}/Books?$select=ID,title,stock
Authorization: Basic viewer:

###
GET {{baseUrl}}{{service}}/Authors
Authorization: Basic viewer:
Accept: application/json

###
GET {{baseUrl}}{{service}}/Orders
Authorization: Basic viewer:

###
GET {{baseUrl}}{{service}}/Orders?$expand=items($expand=book)
authorization: Basic viewer:

### 
POST {{baseUrl}}{{service}}/Orders
Authorization: Basic admin:
Content-Type: application/json

{
    "items": [
        { "book_ID": "22026396-294f-4f7a-8e65-b23c923baf35", "quantity": 2 },
        { "book_ID": "22026397-3b46-4bd6-afbf-eedad1bd3b73",            "quantity": 1 }
    ]
}


###
GET {{baseUrl}}{{service}}/PurchaseLogs?$expand=order
Authorization: Basic viewer:

### 
POST {{baseUrl}}{{service}}/Orders(aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa)/cancelOrder
Authorization: Basic admin:

###
GET {{baseUrl}}{{service}}/Suppliers
Authorization: Basic viewer:
Accept: application/json

###
GET {{baseUrl}}{{service2}}/$metadata
Authorization: Basic viewer:
Accept: application/xml

###
GET {{baseUrl}}{{service2}}/Suppliers
Authorization: Basic viewer:
Accept: application/json

###
GET {{baseUrl}}{{service2}}/Books
Authorization: Basic viewer:
Accept: application/json